# Configuring https://pre-commit.ci/
ci:
    autoupdate_schedule: monthly

exclude: "conf.py"

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: requirements-txt-fixer
          - id: trailing-whitespace
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.2.0
      hooks:
        - id: ruff
          args: [ --config=pyproject.toml ]
    - repo: https://github.com/psf/black
      rev: 24.1.1
      hooks:
          - id: black
            args: [--config=pyproject.toml]
    - repo: https://github.com/codespell-project/codespell
      # Configuration for codespell is in pyproject.toml
      rev: v2.2.6
      hooks:
      - id: codespell
        additional_dependencies:
        - tomli
